[auto_update]
cooldown_days = 7

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-docstring-first" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.12"
hooks = [
  { id = "ruff-check", args = ["--fix", "--show-fixes"] },
]

[[repos]]
repo = "https://github.com/psf/black-pre-commit-mirror"
rev = "26.3.1"
hooks = [{ id = "black-jupyter" }]

[[repos]]
repo = "https://github.com/rbubley/mirrors-prettier"
rev = "v3.8.3"
hooks = [
  { id = "prettier", args = [
    "--cache-location=.prettier_cache/cache",
  ], exclude = "pixi.lock" },
]

[[repos]]
repo = "https://github.com/ComPWA/taplo-pre-commit"
rev = "v0.9.3"
hooks = [
  { id = "taplo-format", args = ["--option", "array_auto_collapse=false"] },
  { id = "taplo-lint", args = ["--no-schema"] },
]

[[repos]]
repo = "https://github.com/zizmorcore/zizmor-pre-commit"
rev = "v1.24.1"
hooks = [
  { id = "zizmor", args = [
    "--offline",
    "--persona=auditor",
    "--fix=all",
  ] },
]
